// Command tubeless-icons is a small in-terminal previewer for every glyph
// tubeless renders — the font's own codepoints plus the procedural sprites
// (box drawing, block elements, powerline, and the symbol fallbacks). Run it
// inside tubeless so the glyphs render through the real atlas:
//
//	tubeless --shell=$(which tubeless-icons)
//
// It's a plain VT text-mode program (same family as cmd/tubeless-config): the
// host renderer paints the glyphs, so this doubles as a coverage test bench —
// anything that renders blank here is genuinely missing from the atlas. Each
// glyph is shown with its hex codepoint underneath; procedural sprites are
// labelled in cyan to tell them apart from font glyphs.
//
// Keys: j/k or arrows scroll, space/b or PgUp/PgDn page, Tab/Shift+Tab or
// left/right switch category, / search by hex or character, q quits.
package main

import (
	"fmt"
	"log"
	"os"
	"os/signal"
	"sort"
	"strings"
	"syscall"

	"golang.org/x/term"

	"github.com/moozd/tubeless/pkg/font"
	"github.com/moozd/tubeless/pkg/platform"
)

const version = "dev"

// Category ids, in tab order.
const (
	catAll = iota
	catBox
	catBlock
	catPowerline
	catSymbols
	catNerd
	catText
	catCount
)

var catNames = [catCount]string{"all", "box", "block", "powerline", "symbols", "nerd", "text"}

const cellW = 9 // columns per glyph cell (glyph + hex label below)

type entry struct {
	r          rune
	cat        int
	procedural bool // generated by font sprites, not from the font cmap
}

type ui struct {
	cols, rows int
	entries    []entry
	filtered   []entry
	cat        int
	query      string
	searching  bool
	top        int
}

func main() {
	if len(os.Args) > 1 && (os.Args[1] == "--version" || os.Args[1] == "-version") {
		fmt.Println("tubeless-icons " + version)
		return
	}
	platform.FixEnv()

	cols, rows, err := term.GetSize(int(os.Stdout.Fd()))
	if err != nil {
		cols, rows = 80, 24
	}

	raw, err := makeRaw(os.Stdin.Fd())
	if err != nil {
		log.Fatalf("raw mode: %v", err)
	}
	defer raw.restore()

	u := &ui{cols: cols, rows: rows, entries: buildEntries()}
	u.rebuild()

	fmt.Fprint(os.Stdout, "\x1b[?1049h\x1b[?25l\x1b[2J")
	defer fmt.Fprint(os.Stdout, "\x1b[?25h\x1b[?1049l")

	sigWin := make(chan os.Signal, 1)
	signal.Notify(sigWin, syscall.SIGWINCH)
	defer signal.Stop(sigWin)

	keys := make(chan byte, 64)
	go readKeys(os.Stdin, keys)

	u.redraw()
	for {
		select {
		case b := <-keys:
			if u.feed(b) {
				fmt.Fprint(os.Stdout, "\x1b[?25h\x1b[?1049l")
				return
			}
		case <-sigWin:
			if c, r, err := term.GetSize(int(os.Stdout.Fd())); err == nil {
				u.cols, u.rows = c, r
			}
		}
		u.redraw()
	}
}

// buildEntries enumerates the font's cmap plus the procedural graphics set,
// deduped and sorted.
func buildEntries() []entry {
	runes, err := font.EnumerateRunes(font.DefaultFontBytes())
	if err != nil {
		log.Fatalf("enumerate font: %v", err)
	}
	seen := map[rune]bool{}
	for _, r := range runes {
		if r >= 0x20 {
			seen[r] = true
		}
	}
	procedural := map[rune]bool{}
	for _, r := range font.GraphicsRunes() {
		seen[r] = true
		procedural[r] = true
	}

	entries := make([]entry, 0, len(seen))
	for r := range seen {
		entries = append(entries, entry{r: r, cat: classify(r), procedural: procedural[r]})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].r < entries[j].r })
	return entries
}

func isPUA(r rune) bool {
	return r >= 0xE000 && r <= 0xF8FF ||
		r >= 0xF0000 && r <= 0xFFFFD ||
		r >= 0x100000 && r <= 0x10FFFD
}

func classify(r rune) int {
	switch {
	case r >= 0x2500 && r <= 0x257F || r == 0x23BF:
		return catBox
	case r >= 0x2580 && r <= 0x259F:
		return catBlock
	case r >= 0xE0B0 && r <= 0xE0D4:
		return catPowerline
	case r == 0x2713 || r == 0x2714 || r == 0x2715 || r == 0x2716 || r == 0x2717 || r == 0x2718 ||
		r == 0x2794 || r == 0x279C || r == 0x279E || r == 0x27A4 || r == 0x27A6 ||
		r == 0x23FA || r == 0x2B24 || r == 0x26AB || r == 0x26A0 ||
		r == 0x2605 || r == 0x2606 || r == 0x2726 || r == 0x2727 ||
		r == 0x23F8 || r == 0x23F9:
		return catSymbols
	case isPUA(r):
		return catNerd
	default:
		return catText
	}
}

// rebuild recomputes the filtered list from cat + query.
func (u *ui) rebuild() {
	q := strings.ToLower(u.query)
	u.filtered = u.filtered[:0]
	for _, e := range u.entries {
		if u.cat != catAll && e.cat != u.cat {
			continue
		}
		if q != "" && !matches(e.r, q) {
			continue
		}
		u.filtered = append(u.filtered, e)
	}
	u.top = clampTop(u.top, len(u.filtered), u)
}

func matches(r rune, q string) bool {
	if strings.Contains(strings.ToLower(string(r)), q) {
		return true
	}
	return strings.Contains(strings.ToLower(fmt.Sprintf("U+%04X", r)), q)
}

func (u *ui) gridDims() (cols, rows int) {
	cols = u.cols / cellW
	if cols < 1 {
		cols = 1
	}
	rows = (u.rows - 4) / 2
	if rows < 1 {
		rows = 1
	}
	return
}

func (u *ui) pageHeight() int {
	cols, rows := u.gridDims()
	return cols * rows
}

func clampTop(top, total int, u *ui) int {
	lim := total - u.pageHeight()
	if top < 0 {
		return 0
	}
	if top > lim {
		return max(0, lim)
	}
	return top
}

func (u *ui) feed(b byte) (quit bool) {
	switch {
	case u.searching:
		switch b {
		case 0x1b, '\r', '\n':
			u.searching = false
		case 0x7f, 0x08:
			if len(u.query) > 0 {
				u.query = u.query[:len(u.query)-1]
				u.top = 0
				u.rebuild()
			}
		default:
			if b >= 0x20 && b < 0x7f {
				u.query += string(b)
				u.top = 0
				u.rebuild()
			}
		}
		return false
	case b == 0x1b:
		return u.feedEscape()
	}
	return u.feedKey(b)
}

func (u *ui) feedKey(b byte) (quit bool) {
	switch b {
	case 'q', 0x03: // q or Ctrl-C
		return true
	case '/':
		u.searching = true
	case 'j', 0x0e: // down one row
		u.scrollBy(u.rowStep())
	case 'k', 0x10: // up one row
		u.scrollBy(-u.rowStep())
	case ' ', 0x0c: // page down
		u.scrollBy(u.pageHeight())
	case 'b': // page up (vi convention)
		u.scrollBy(-u.pageHeight())
	case '\t':
		u.switchCat(u.cat + 1)
	}
	return false
}

func (u *ui) feedEscape() (quit bool) {
	b := readByteBlock(os.Stdin)
	if b != '[' {
		u.searching = false
		return false
	}
	switch f := readByteBlock(os.Stdin); f {
	case 'A': // up
		u.scrollBy(-u.rowStep())
	case 'B': // down
		u.scrollBy(u.rowStep())
	case 'D': // left = previous category
		u.switchCat(u.cat - 1)
	case 'C': // right = next category
		u.switchCat(u.cat + 1)
	case '5', '6': // PgUp / PgDn
		readByteBlock(os.Stdin) // trailing '~'
		if f == '5' {
			u.scrollBy(-u.pageHeight())
		} else {
			u.scrollBy(u.pageHeight())
		}
	case 'Z': // Shift+Tab = previous category
		u.switchCat(u.cat - 1)
	}
	return false
}

func (u *ui) rowStep() int {
	cols, _ := u.gridDims()
	return cols
}

func (u *ui) switchCat(c int) {
	c = (c%catCount + catCount) % catCount
	u.cat = c
	u.top = 0
	u.rebuild()
}

func (u *ui) scrollBy(n int) {
	u.top = clampTop(u.top+n, len(u.filtered), u)
}

func (u *ui) redraw() {
	var b strings.Builder
	b.WriteString("\x1b[2J\x1b[H")

	// Title + category tabs.
	b.WriteString("\x1b[1mtubeless icons\x1b[0m")
	for i, name := range catNames {
		if i == u.cat {
			b.WriteString(fmt.Sprintf("  \x1b[7m %s \x1b[0m", name))
		} else {
			b.WriteString(fmt.Sprintf("  \x1b[2m%s\x1b[0m", name))
		}
	}

	// Search / hint line.
	switch {
	case u.searching:
		b.WriteString(fmt.Sprintf("\r\nsearch: %s_", u.query))
	case u.query != "":
		b.WriteString(fmt.Sprintf("\r\n\x1b[2mfilter: %s  (/ to edit)\x1b[0m", u.query))
	default:
		b.WriteString("\r\n\x1b[2m/ search · j/k scroll · Tab category · q quit\x1b[0m")
	}

	// Glyph grid.
	cols, rows := u.gridDims()
	for i := 0; i < rows*cols; i++ {
		idx := u.top + i
		if idx >= len(u.filtered) {
			break
		}
		e := u.filtered[idx]
		row, col := i/cols, i%cols
		gy, ly := 3+row*2, 4+row*2
		gx := col*cellW + 1
		b.WriteString(fmt.Sprintf("\x1b[%d;%dH%s", gy, gx, string(e.r)))
		hex := fmt.Sprintf("U+%04X", e.r)
		if e.procedural {
			b.WriteString(fmt.Sprintf("\x1b[%d;%dH\x1b[36m%s\x1b[0m", ly, gx, hex))
		} else {
			b.WriteString(fmt.Sprintf("\x1b[%d;%dH\x1b[2m%s\x1b[0m", ly, gx, hex))
		}
	}

	// Status line.
	proceduralCount := 0
	for _, e := range u.filtered {
		if e.procedural {
			proceduralCount++
		}
	}
	total := len(u.filtered)
	shown := min(rows*cols, max(0, total-u.top))
	b.WriteString(fmt.Sprintf("\x1b[%d;1H\x1b[2m%d glyphs (%d procedural) · showing %d–%d\x1b[0m",
		u.rows, total, proceduralCount, u.top+1, u.top+shown))

	os.Stdout.WriteString(b.String())
}

// ---------------- terminal plumbing ----------------

type rawState struct {
	fd    int
	state *term.State
}

func makeRaw(fd uintptr) (*rawState, error) {
	state, err := term.MakeRaw(int(fd))
	if err != nil {
		return nil, err
	}
	return &rawState{fd: int(fd), state: state}, nil
}

func (r *rawState) restore() { term.Restore(r.fd, r.state) }

func readKeys(f *os.File, out chan<- byte) {
	buf := make([]byte, 256)
	for {
		n, err := f.Read(buf)
		for i := 0; i < n; i++ {
			out <- buf[i]
		}
		if err != nil {
			return
		}
	}
}

// readByteBlock reads a single byte from stdin, blocking.
func readByteBlock(f *os.File) byte {
	var one [1]byte
	f.Read(one[:])
	return one[0]
}
